logging:
  level:
    root: INFO
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:~/test;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    data: classpath:data/author-h2.sql, classpath:data/post-h2.sql